version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopify-destio
    container_name: shopify-destio
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  database:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: shopify_user
      MONGO_INITDB_ROOT_PASSWORD: shopify_password
      MONGO_INITDB_DATABASE: shopify_db
